from . import sale_order
from . import sale_order_line
from . import account_move
from . import res_config_settings
from . import product_template
from . import product_supplierinfo
from . import stock_warehouse
from . import stock_warehouse_orderpoint
from . import stock_picking
