{
    'name': 'Productividad',
    'version': '17.0.7.0',
    'summary': 'Gestión de la productividad diaria',
    'description': 'Permite configurar y hacer seguimiento de metas diarias por mes.',
    'category': 'Productivity',
    'author': 'Distribuciones Hoyostools Sas',
    'depends': ['base', 'stock', 'sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/productividad_turno_views.xml',
        'views/configuracion_meta_views.xml',
        'views/tablero_configuracion_views.xml',
        'views/seguimiento_empacador_views.xml',
        'views/resumen_empacador_mensual_views.xml',
        'views/errores_picking_views.xml',
        'views/seguimiento_picking_views.xml',
        'views/errores_packing_views.xml',
        'views/seguimiento_almacenamiento_views.xml',
        'views/productividad_combo_pasillo_views.xml',
        'views/stock_picking_inherit.xml',
        'views/productividad_menus.xml',
    ],
    'icon': 'productividad/static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
